services:
  mysql:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yapgoon
      MYSQL_DATABASE: yapgoon_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: yapgoon

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  client:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - server